import os
import secrets
import sqlite3

from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import urlencode


DATABASE_PATH = (
    Path(__file__).resolve().parent.parent
    / "database"
    / "bot.db"
)

OSU_AUTHORIZE_URL = "https://osu.ppy.sh/oauth/authorize"

OSU_CLIENT_ID = os.getenv("OSU_CLIENT_ID")
OSU_REDIRECT_URI = os.getenv("OSU_REDIRECT_URI")


class OsuOAuth:
    STATE_LIFETIME_MINUTES = 10

    @staticmethod
    def validate_configuration() -> None:
        missing = []

        if not OSU_CLIENT_ID:
            missing.append("OSU_CLIENT_ID")

        if not OSU_REDIRECT_URI:
            missing.append("OSU_REDIRECT_URI")

        if missing:
            raise RuntimeError(
                "Missing OAuth environment variables: "
                + ", ".join(missing)
            )

    @staticmethod
    def create_authorization_url(
        discord_id: int,
        guild_id: int,
    ) -> str:
        OsuOAuth.validate_configuration()

        state = secrets.token_urlsafe(32)

        now = datetime.now(timezone.utc)
        expires_at = now + timedelta(
            minutes=OsuOAuth.STATE_LIFETIME_MINUTES
        )

        with sqlite3.connect(DATABASE_PATH) as connection:
            # Remove old links generated by this Discord account.
            connection.execute(
                """
                DELETE FROM osu_oauth_states
                WHERE discord_id = ?
                """,
                (discord_id,),
            )

            # Remove all expired states.
            connection.execute(
                """
                DELETE FROM osu_oauth_states
                WHERE expires_at <= ?
                """,
                (now.isoformat(),),
            )

            connection.execute(
                """
                INSERT INTO osu_oauth_states (
                    state,
                    discord_id,
                    guild_id,
                    created_at,
                    expires_at
                )
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    state,
                    discord_id,
                    guild_id,
                    now.isoformat(),
                    expires_at.isoformat(),
                ),
            )

        query = urlencode(
            {
                "client_id": OSU_CLIENT_ID,
                "redirect_uri": OSU_REDIRECT_URI,
                "response_type": "code",
                "scope": "public identify",
                "state": state,
            }
        )

        return f"{OSU_AUTHORIZE_URL}?{query}"